[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.6.4",
    "pandas>=2.3.3",
    "py-cord>=2.6.1",
    "requests>=2.32.5",
]
